# Generated by Django 4.1.7 on 2023-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='quote',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
