# Generated by Django 4.1.7 on 2023-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_remove_quote_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
