# Generated by Django 4.1.7 on 2023-04-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quote_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='contact',
            field=models.CharField(blank=True, default='El mismo', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.TextField(blank=True, default='Dólares', max_length=16),
        ),
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quote',
            name='unit',
            field=models.CharField(blank=True, default='$', max_length=4),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
