# Generated by Django 4.1.7 on 2023-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_alter_item_price_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
